# litellm_tool_fix.py
"""
LiteLLM callback to fix null tool descriptions for Harmony protocol compatibility.

The vLLM Harmony protocol requires every ToolDescription.description to be a
non-null string. Some tools generated by the Claude Code CLI have description=None,
causing a pydantic ValidationError. This callback patches those before the request
reaches vLLM.

Register in your LiteLLM proxy config:

    litellm_settings:
      callbacks: ["litellm_tool_fix.HarmonyToolFixer"]
"""
from litellm.integrations.custom_logger import CustomLogger


class HarmonyToolFixer(CustomLogger):
    def log_pre_api_call(self, model, messages, kwargs):
        tools = kwargs.get("tools") or kwargs.get("optional_params", {}).get("tools")
        if not tools:
            return
        for tool in tools:
            func = tool.get("function", {})
            if func.get("description") is None:
                func["description"] = func.get("name", "tool") + " - no description available"
